### PR TITLE
Markdown-ize README, document installing packages

### LINKED ISSUE #13: Allow to installation of more packages into a venv
Say I have installed beet (http://beets.radbox.org/) with pipsi. beet has some optional dependencies which need to be installed if you enable one of the provided plugins. To use discogs you need the discogs-client package, to use lastgenre you need the pylast package.

So, in order to use those plugins it should be possible to install more packages into the venv.

### PR DESCRIPTION
**Pull request by lorin**
Format the README as markdown so it renders nicely on GitHub.

Document how to add additional packages to an existing venv.

Fixes  #13.

I originally intended to just document how to add additional packages to the venv, but then I felt compelled to do the markdown formatting.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
thanks for the work, but it needs to be restructuredtext since its also what goes to the pypi description

**Comment by lorin** [comment]
@RonnyPfannschmidt How about if I reStructuredText-ized it instead (and gave it an .rst extension so github rendered it nicely)?

**Comment by untitaker** [comment]
I think that'd be fine.

**Comment by RonnyPfannschmidt** [comment]
yup

**Comment by lorin** [comment]
See #43

**Pull request closed without merging**
