### PR TITLE
Save a list of linked scripts in package-info.json

### PR DESCRIPTION
**Pull request by pfmoore**

### CODE REVIEW

**Comment by pfmoore** [comment]
Initial implementation. I have done some manual testing so far, but I need to work out how to run the test suite and how to add tests for the new functionality (not sure if this is feasible, as the only place behaviour will differ is on Windows, and there's no Appveyor testing).

I'll also see how the Travis tests fare...

**Comment by pfmoore** [comment]
Test failures appear to be due to Travis not being able to install some of the Python environments - I'm not sure why. Running the tests locally (Windows) mostly seems to work, but there are some failures from things like "Attic" not being buildable on my PC.

I'm not sure I can do much more in terms of testing here. What I *am* inclined to do is to expand the test suite and tidy it up a bit. I'll do this in my clone, see how I go and then produce a PR for that (probably enabling appveyor support as well, for my own benefit if nothing else ;-))

**Comment by pfmoore** [comment]
What's the next step with this PR? I don't know how to address the build failures, I'm afraid. Any pointers?

**Comment by RonnyPfannschmidt** [comment]
sorry for the long wait, i hope to take  a look this weekend, im a bit swamped in personal time

**Comment by pfmoore** [comment]
No, it's fine. No rush at all. In the meantime I'll see if I can work out why those tests are failing. It seems to be something in master, so I'll dig around there.

**Comment by pfmoore** [comment]
Found the Travis issue - it's to do with how Travis sets up Python. I've created #112 that fixes this.

**Comment by pfmoore** [comment]
Rebased to pick up the test fixes in master

**Comment by pfmoore** [comment]
Is there anything more I need to do on this issue? It looks like there were merge conflicts with master, but I did a merge locally and it seems to have worked, so I think the PR is up to date with master again.

**Comment by RonnyPfannschmidt** [comment]
thanks for the ping, i just missed the change

**Comment by pfmoore** [comment]
No problem - thanks for merging!

Does pipsi have formal releases that I should wait for to see this change, or should I simply be tracking master? The docs say "pipsi upgrade pipsi", but I assume this only works for getting the latest version from PyPI? How would I upgrade to master? Is there a better way than
```
~\.local\venvs\pipsi\Scripts\python.exe -m pip install -U https://github.com/mitsuhiko/pipsi
```
?

(Hmm, it just occurred to me that this change may have broken `pipsi upgrade FOO` if pipsi gets upgraded to the new version after installing FOO, because the installed scripts metadata won't be present in the currently installed version of FOO, so uninstalling might break. My instincts are that manually removing and then reinstalling FOO would be sufficient, but I haven't put a lot of thought into it - does that seem reasonable?)

**Comment by RonnyPfannschmidt** [comment]
@pfmoore that issue is a correct observation - i believe its necessary to restore the old functionality for removing linked files, as far as i can tell the issue happens always on windows as well as on other platforms without symlinks

i propose a utility method that tries metadata and falls back to the old implementation

**Comment by pfmoore** [comment]
OK, I'll look into that.

**Comment by pfmoore** [comment]
OK. #122 created for that.

Actually, upgrade worked fine because it just looks for differences in the installed scripts (so we just don't get the new metadata on upgrade). But I'm happier with the backward compatibility fallback in anyway, so no harm done.

To get new metadata *does* need an uninstall/reinstall of existing packages, but pipsi still works without that step. It's just that if you don't reinstall, `pipsi uninstall` won't uninstall exe wrappers on Windows without this change, so if you uninstall without reinstalling, you end up with broken exes in `PATH` (same as you would have done before any of these changes).

**Comment by RonnyPfannschmidt** [comment]
thanks - as a note - for personal reasons i probably wont have time to do more than basic review/merges/suggestions until the end if january, afterwards i hope to get into releasing, its kinda overdue

**Comment by pfmoore** [comment]
No problem, I just updated from master so there's no pressure from me.

**Pull request merged**
