### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by fpatz**
Added support for Windows paths and the layout of the Python tree on Windows. Package installation works well. With Python 2, which lacks `os.symlink()` on Windows, listing packages does not work, and uninstalling packages does not remove executables from ``~/.local/bin``, since executables are copied in that case.

### CODE REVIEW

**Comment by untitaker** [comment]
Please coordinate with #32.

**Comment by RonnyPfannschmidt** [comment]
mine is more complete and includes unit/acceptance tests

**Comment by fpatz** [comment]
Thanks for the hint -- I didn't notice the other PR. @RonnyPfannschmidt, anything I could do to help with yours?

**Comment by RonnyPfannschmidt** [comment]
mine mostly needs detail tests/potentially additional tests for the commands
once its merged i intend to add a minimalist package management control thing

**Pull request closed without merging**
