### PR TITLE
Add --suffix-version option

### PR DESCRIPTION
**Pull request by caioariede**
Simple approach that enables installation for multiple Python versions.

### CODE REVIEW

**Comment by caioariede** [comment]
Tests failed because of environment py33 that does not exist.

**Comment by caioariede** [comment]
Example:

```bash
$ git clone https://github.com/caioariede/pipsi.git /tmp/pipsi
$ cd /tmp/pipsi
$ git checkout feature/add-suffix-py-version
$ python3 get-pipsi.py --suffix-version --src ./
Installing pipsi-3.6.5
...
$ pipsi-3.6.5 --version
pipsi-3.6.5, version 0.10.dev0, python ...
$ pipsi-3.6.5 install flake8
...
$ which flake8-3.6.5
/Users/caio/.local/bin/flake8-3.6.5
```

**Comment by RonnyPfannschmidt** [comment]
imho pipsi should only be required to be installed once, the python versions should only be needed for tehe programs

**Comment by reorx** [comment]
In my opinion what `get-pipsi.py` installed should also be able to managed by `pipsi` itself, and since pipsi doesn't support installing packages for multiple versions, e.g. install and keep `flake8` in 3.6.0 and 3.5.0 at the same time, we should not break the package dir naming.

When pipsi support multiple package versions, then you can `pipsi install pipsi==0.9` and get a `pipsi-0.9` on your path, I think this should be a better approach, and is more useful than only let `get-pipsi.py` support multiple versions.

**Pull request closed without merging**
