### PR TITLE
Load configuration from ~/.pipsirc

### PR DESCRIPTION
**Pull request by juliocc**
Give pipsi the ability to load your config (home and bin directories) from a configuration file.

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
can you use the XDG_CONFIG_HOME if possible?

**Comment by juliocc** [comment]
Couple of questions:
1. What should be the fallback if XDG_CONFIG_HOME is not defined? What if we're on a Windows environment?
2. How do you suggest we determine XDG_CONFIG_HOME? I found pyxdg[1] but I don't know if we want to introduce another dependency.

[1] http://pyxdg.readthedocs.org/en/latest/basedirectory.html#configuration-directories

**Comment by ryneeverett** [comment]
> 2. How do you suggest we determine XDG_CONFIG_HOME? I found pyxdg[1] but I don't know if we want to introduce another dependency.

`os.environ`?

**Comment by RonnyPfannschmidt** [comment]
since we only should care about xdg config home, just caring about that env var and the default should be fine

**Comment by benwebber** [comment]
This needs to be updated to account for the recent Windows support.

If #48 is merged before this, I suggest the following search path:

1. command line flags (`--home`, `--bin-dir`)
2. `PIPSI_HOME` / `PIPSI_BIN_DIR` environment variables
3. XDG-style configuration file
4. Pipsi defaults

**Comment by juliocc** [comment]
I haven't had time to get back this again but I want to use [user_config_dir](https://github.com/pypa/pip/blob/develop/pip/utils/appdirs.py#L132) from pip's source code which should handle Linux, OS X and Windows.

**Comment by RonnyPfannschmidt** [comment]
@juliocc what's the status on this?

**Comment by RonnyPfannschmidt** [comment]
Also we should conside mitsuhiko/click#386

**Comment by RonnyPfannschmidt** [comment]
This Can be reopened when bit rot is over

**Pull request closed without merging**
