### PR TITLE
Allow user to specify different PYPI server

### PR DESCRIPTION
**Pull request by alex8080**

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
without prior support for storing such details for the upgrade, command we cant properly support that except for global pip.conf, which already works right now

**Comment by RonnyPfannschmidt** [comment]
@alex8080 ping? any interest in driving this further?

**Comment by alex8080** [comment]
@RonnyPfannschmidt Yep, I enjoy this little enhancement and think it is useful. Would you mind helping me better understand your original comment?

**Comment by RonnyPfannschmidt** [comment]
the problem is, that if you install using a alternate server its all fine
but as soon as you run a update later, we no longer know the alternate server and might break things

**Comment by alex8080** [comment]
@RonnyPfannschmidt would you like me to add/change anything on this pull request?

**Comment by dan-passaro** [comment]
> the problem is, that if you install using a alternate server its all fine
but as soon as you run a update later, we no longer know the alternate server and might break things

I think that would be on the user to maintain. When upgrading, Pipsi either it can find a newer package or it can't at whatever index it's told to check. It's up to the user to point it at the right index. I don't think maintaining the originally installed index should be a feature of the tool, especially since there might be cases where you *do* want to update from a different index than the one you installed from.

**Comment by alex8080** [comment]
@dan-passaro I completely agree with you and it is exactly what I have done. 
In my original change there was no way of alternative server specification during upgrade. My interpretation of @RonnyPfannschmidt comment was that the tool should **allow to specify** alternative server during upgrade and **not remember** the one which was used for installation.

**Pull request closed without merging**
